### ISSUE TITLE
HMR doesn't rebuild tailwind

### ISSUE THREAD

**Issue by JasonHorsleyTech** [def-studio/vite-livewire-plugin#21]
## Steps

[Here's a slimmed down repo I made for demo purposes](https://github.com/JasonHorsleyTech/vite-livewire-plugin-example-bug) based off the default laravel-9 installation.

* Create new laravel+livewire+vite+tailwind project, add this plugin

* Sail up, sail npm run dev, go to example-app.test
* You should see a simple label and text area

<img width="288" alt="Screen Shot 2022-08-18 at 5 02 27 PM" src="https://user-images.githubusercontent.com/32709073/185503038-af43685d-a098-4d8b-b7e0-aecbea164d56.png">

* Enter text in textarea from browser, then make a code update inside show-posts.blade.php changing h2.innerText
> from ```Make a post.``` to ```Make a post!!!```
* Livewire component updates without clearing the textarea (yay)

* Add a tailwindcss class that *didn't* exist when you started build
* > ```<h1 class="text-3xl my-2">``` to ```<h1 class="text-3xl my-2 text-[#FF0000]">```
* Livewire component updates, the HTML on the page changes, and the new class is on the H1 element (yay)

* **BUG:** Tailwind did *not* rebuild and app.css has no such .text[#FF0000] class (boo)

---

* Restart your npm run dev
* Page reloads and text is now red

**Comment by fabio-ivona** [comment]
Hi @JasonHorsleyTech thanks for pointing this out, I'll be back from vacation on 22nd of August and will check it soon

**Comment by fabio-ivona** [comment]
we have detected the source of the issue and we are working with Vite team to solve it, I'll share an update soon

**Comment by fabio-ivona** [comment]
a fix has been released in v0.2.5
